const KEY = 'kanaklata-puja-receipts-v1';
const SETTINGS_KEY = 'kanaklata-puja-settings-v1';
let receipts = JSON.parse(localStorage.getItem(KEY) || '[]');
let settings = JSON.parse(localStorage.getItem(SETTINGS_KEY) || '{"year":"2026","collector":"Puja Committee","secretary":"Secretary, Kanaklata Heights Residents Durga Puja Committee"}');
let currentReceipt = null;
let editingId = null;
const $ = id => document.getElementById(id);
const money = n => '₹' + Number(n).toLocaleString('en-IN');
const dateText = iso => new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric'}).format(new Date(iso));
function save(){ localStorage.setItem(KEY, JSON.stringify(receipts)); }
function renderList(){
  const total = receipts.reduce((sum,r)=>sum+Number(r.amount),0);
  $('totalCollected').textContent=money(total); $('receiptCount').textContent=receipts.length;
  $('latestNumber').textContent=receipts.length ? receipts[0].number : '—';
  $('recentReceipts').innerHTML=receipts.length ? receipts.slice(0,5).map(r=>`<button class="list-item" data-id="${r.id}"><span class="initial">${r.name.trim()[0].toUpperCase()}</span><span><b>${esc(r.name)}</b><small>${r.number} · ${dateText(r.date)} · ${esc(r.paymentMode)}</small></span><strong>${money(r.amount)}</strong></button>`).join('') : '<div class="empty">No receipts yet. Your generated receipts will be securely saved on this device.</div>';
  document.querySelectorAll('.list-item').forEach(el=>el.onclick=()=>showReceipt(receipts.find(r=>r.id===el.dataset.id)));
}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function words(n){
  const ones=['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen']; const tens=['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];
  const two=x=>x<20?ones[x]:tens[Math.floor(x/10)]+(x%10?' '+ones[x%10]:''); const three=x=>x>=100?ones[Math.floor(x/100)]+' Hundred'+(x%100?' '+two(x%100):''):two(x);
  if(n===0)return 'Zero'; if(n>99999999)return String(n); let out=''; if(Math.floor(n/100000)>0){out+=three(Math.floor(n/100000))+' Lakh ';n%=100000}if(Math.floor(n/1000)>0){out+=two(Math.floor(n/1000))+' Thousand ';n%=1000}return (out+three(n)).trim();
}
function showReceipt(r){
  currentReceipt=r; const isShared=!r.id; $('detailTitle').textContent=r.number;
  $('receiptCard').innerHTML=`<div class="receipt-top"><div><p class="eyebrow">SHARODOTSAV ${esc(r.year)}</p><h3>Kanaklata Heights</h3><small>Residents · Narendrapur, Kolkata – 700103</small></div><div class="receipt-no">${esc(r.number)}<br><small>${dateText(r.date)}</small></div></div><div class="receipt-body"><p>Received with gratitude from <b>${esc(r.name)}</b></p><p>towards <b>${esc(r.purpose)}</b></p><p>Payment date: <b>${dateText(r.date)}</b></p><p>Payment mode: ${esc(r.paymentMode)}${r.notes ? ' · '+esc(r.notes):''}</p><p class="amount-words">Rupees ${words(Number(r.amount))} only</p><b>${money(r.amount)}</b></div><div class="receipt-footer"><span>Collector<br><b>${esc(r.collector)}</b></span><span style="text-align:right">Secretary<br><b>${esc(r.secretary)}</b></span></div>`;
  $('toggleActions').hidden=isShared; document.querySelector('.share-actions').hidden=true; $('recordActions').hidden=true; $('receiptLinkNote').hidden=true; $('detailDialog').showModal();
}
function encodeReceipt(r){const copy={number:r.number,date:r.date,year:r.year,collector:r.collector,secretary:r.secretary,name:r.name,amount:r.amount,paymentMode:r.paymentMode,purpose:r.purpose,notes:r.notes};return btoa(String.fromCharCode(...new TextEncoder().encode(JSON.stringify(copy)))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function decodeReceipt(value){try{const base=value.replaceAll('-','+').replaceAll('_','/'),padded=base+'='.repeat((4-base.length%4)%4);return JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(padded),c=>c.charCodeAt(0))))}catch{return null}}
function detailedReceiptUrl(r){return location.href.split('#')[0].split('?')[0]+'#receipt='+encodeReceipt(r)}function receiptUrl(r){if(r.shortUrl)return Promise.resolve(r.shortUrl);const longUrl=detailedReceiptUrl(r);return new Promise(resolve=>{const callback='pujaShortUrl'+Date.now(),script=document.createElement('script');let settled=false;const finish=value=>{if(settled)return;settled=true;delete window[callback];script.remove();resolve(value)};window[callback]=data=>{const shortUrl=data?.shorturl;if(shortUrl?.startsWith('https://')){r.shortUrl=shortUrl;if(r.id)save();finish(shortUrl)}else finish(longUrl)};script.onerror=()=>finish(longUrl);script.src='https://is.gd/create.php?format=json&callback='+callback+'&url='+encodeURIComponent(longUrl);document.head.appendChild(script);setTimeout(()=>finish(longUrl),10000)})}
function message(r,link){return `Namaskar ${r.name}, thank you for your contribution of ${money(r.amount)} towards ${r.purpose} for Kanaklata Heights Sharodotsav ${r.year}. Receipt ${r.number}: ${link}`}
async function receiptImage(r){const width=1200,height=840,canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const c=canvas.getContext('2d');c.fillStyle='#fff8ea';c.fillRect(0,0,width,height);c.fillStyle='#8b1620';c.fillRect(0,0,width,165);c.fillStyle='#e89b24';c.fillRect(0,165,width,11);c.fillStyle='#ffd975';c.font='bold 29px sans-serif';c.fillText('SHARODOTSAV '+r.year,60,60);c.fillStyle='white';c.font='700 52px Georgia';c.fillText('Kanaklata Heights',60,117);c.font='24px sans-serif';c.fillText('Residents · Narendrapur, Kolkata – 700103',60,148);c.fillStyle='#8b1620';c.font='700 27px sans-serif';c.fillText('DIGITAL DONATION RECEIPT',60,220);c.textAlign='right';c.fillText(r.number,width-60,220);c.textAlign='left';c.strokeStyle='#d7bd88';c.lineWidth=2;c.setLineDash([10,9]);c.beginPath();c.moveTo(60,245);c.lineTo(width-60,245);c.stroke();c.setLineDash([]);const lines=[`Received with gratitude from: ${r.name}`,`Towards: ${r.purpose}`,`Payment mode: ${r.paymentMode}${r.notes?' · '+r.notes:''}`,`Rupees ${words(Number(r.amount))} only`];let y=325;c.fillStyle='#4c4034';c.font='27px sans-serif';for(const line of lines){for(const row of wrap(c,line,1060)){c.fillText(row,60,y);y+=40}y+=9}c.fillStyle='#216343';c.font='bold 65px sans-serif';c.fillText(money(r.amount),60,590);c.fillStyle='#8b1620';c.fillRect(0,675,width,165);c.fillStyle='#fff6df';c.font='italic 30px Georgia';c.fillText('Your gracious presence at Puja Mandap is highly solicited',60,735);c.font='22px sans-serif';c.fillText('Collector: '+r.collector,60,795);c.textAlign='right';c.fillText('Secretary: '+r.secretary,width-60,795);c.textAlign='left';const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));return new File([blob],`${r.number}.png`,{type:'image/png'})}
function wrap(c,text,max){const words=text.split(' '),rows=[];let row='';for(const word of words){const next=row?row+' '+word:word;if(c.measureText(next).width>max&&row){rows.push(row);row=word}else row=next}if(row)rows.push(row);return rows}
function openNew(){ editingId=null; $('receiptForm').reset(); $('receiptDialog').showModal(); }
$('newReceiptButton').onclick=openNew; document.querySelector('[data-view="new"]').onclick=openNew;
$('receiptForm').onsubmit=e=>{e.preventDefault(); const data=new FormData(e.target); const existing=editingId&&receipts.find(r=>r.id===editingId); const r={...(existing||{}),id:existing?.id||crypto.randomUUID(),number:existing?.number||'KH-'+settings.year+'-'+String(receipts.length+1).padStart(4,'0'),date:existing?.date||new Date().toISOString(),year:existing?.year||settings.year,collector:settings.collector,secretary:settings.secretary,name:data.get('name').trim(),amount:data.get('amount'),paymentMode:data.get('paymentMode'),phone:data.get('phone').replace(/\D/g,''),purpose:data.get('purpose'),notes:data.get('notes').trim()}; if(existing)receipts=receipts.map(x=>x.id===r.id?r:x);else receipts.unshift(r); editingId=null;save();renderList();$('receiptDialog').close();showReceipt(r)};
$('closeDetail').onclick=()=>$('detailDialog').close();
$('editButton').onclick=()=>{const r=currentReceipt;if(!r?.id)return;editingId=r.id;$('donorName').value=r.name;$('donationAmount').value=r.amount;$('paymentMode').value=r.paymentMode;$('donorPhone').value=r.phone||'';$('purpose').value=r.purpose;$('notes').value=r.notes||'';$('detailDialog').close();$('receiptDialog').showModal();};
$('deleteButton').onclick=()=>{const r=currentReceipt;if(!r?.id)return;if(!confirm(`Delete receipt ${r.number}? This cannot be undone unless you restore a backup.`))return;receipts=receipts.filter(x=>x.id!==r.id);save();renderList();$('detailDialog').close();};
$('toggleActions').onclick=()=>{const visible=!document.querySelector('.share-actions').hidden;document.querySelector('.share-actions').hidden=visible;$('recordActions').hidden=visible;};
$('whatsappButton').onclick=async()=>{const r=currentReceipt,link=await receiptUrl(r),phone=r.phone?'91'+r.phone:'';window.open(`https://wa.me/${phone}?text=${encodeURIComponent(message(r,link))}`,'_blank')};
$('smsButton').onclick=async()=>{const r=currentReceipt,link=await receiptUrl(r);location.href=`sms:${r.phone||''}?body=${encodeURIComponent(message(r,link))}`};
$('nativeShareButton').onclick=async()=>{const link=await receiptUrl(currentReceipt);if(navigator.share) await navigator.share({title:`Puja receipt ${currentReceipt.number}`,text:message(currentReceipt,link),url:link});else await navigator.clipboard.writeText(message(currentReceipt,link));};
$('imageShareButton').onclick=async()=>{const r=currentReceipt,file=await receiptImage(r),link=await receiptUrl(r);if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:`Puja receipt ${r.number}`,text:message(r,link),files:[file]});else{const a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=file.name;a.click();URL.revokeObjectURL(a.href)}};
$('printButton').onclick=()=>window.print();
$('settingsButton').onclick=()=>{$('settingYear').value=settings.year;$('settingCollector').value=settings.collector;$('settingSecretary').value=settings.secretary;$('settingsDialog').showModal()};
$('closeSettings').onclick=()=>$('settingsDialog').close();$('saveSettings').onclick=()=>{settings={year:$('settingYear').value||'2026',collector:$('settingCollector').value||'Puja Committee',secretary:$('settingSecretary').value||'Secretary'};localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));$('settingsDialog').close();};
$('exportButton').onclick=()=>{const data=JSON.stringify({exportedAt:new Date().toISOString(),settings,receipts},null,2),file=new Blob([data],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=`kanaklata-puja-backup-${settings.year}.json`;a.click();URL.revokeObjectURL(a.href)};
$('importButton').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.receipts))throw new Error();if(!confirm(`Restore ${data.receipts.length} receipts from this backup? This replaces current records.`))return;receipts=data.receipts;settings=data.settings||settings;save();localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));renderList();$('settingsDialog').close();alert('Backup restored successfully.')}catch{alert('That backup file is not valid.')}finally{e.target.value=''}};
$('viewAllButton').onclick=()=>{document.querySelector('.records-section').scrollIntoView({behavior:'smooth'});};document.querySelector('[data-view="records"]').onclick=()=>document.querySelector('.records-section').scrollIntoView({behavior:'smooth'});document.querySelector('[data-view="home"]').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});
const sharedPayload=new URLSearchParams(location.hash.slice(1)).get('receipt');if(sharedPayload){const shared=decodeReceipt(sharedPayload);if(shared)setTimeout(()=>showReceipt(shared),150)}
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw-v2.js'); renderList();
